# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='autorespond_postings',
        ),
        migrations.RemoveField(
            model_name='list',
            name='autorespond_requests',
        ),
        migrations.RemoveField(
            model_name='list',
            name='autoresponse_postings_text',
        ),
        migrations.RemoveField(
            model_name='list',
            name='autoresponse_request_text',
        ),
        migrations.RemoveField(
            model_name='list',
            name='digest_is_default',
        ),
        migrations.RemoveField(
            model_name='list',
            name='digest_last_sent_at',
        ),
        migrations.RemoveField(
            model_name='list',
            name='digest_volume_frequency',
        ),
        migrations.RemoveField(
            model_name='list',
            name='digestable',
        ),
        migrations.RemoveField(
            model_name='list',
            name='send_goodbye_message',
        ),
        migrations.RemoveField(
            model_name='list',
            name='send_welcome_message',
        ),
    ]
