# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 17:12
from __future__ import unicode_literals

from django.db import migrations

import holonet.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20160201_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=holonet.core.fields.DomainField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set([('list_name', 'domain')]),
        ),
    ]
