tasks:
  - tox -e tests
  - tox -e isort
  - tox -e flake8
  - coverage report --fail-under=75
  - coverage xml

verbose_tasks:
  - coverage report --fail-under=75

comment: false

services:
  - postgresql
  - redis-server

coverage:
  path: coverage.xml
  parser: python
