tasks:
  - tox -e tests
  - tox -e isort
  - tox -e flake8
  - tox -e coverage

verbose_tasks:
  - tox -e coverage

comment: false

services:
  - postgresql
  - redis-server

coverage:
  path: coverage.xml
  parser: python
