tasks:
  - tox -e py34
  - tox -e docs
  - flake8
  - isort -c -rc holonet
  - coverage report --fail-under=75
  - coverage xml
  - npm run lint

comment: false

services:
  - postgresql
  - redis-server

coverage:
  path: coverage.xml
  parser: python
