version: '2'

services:
  postgres:
    image: postgres:9.5
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_USER=holonet

  redis:
    image: redis:latest
    ports:
      - '127.0.0.1:6379:6379'

  elasticsearch:
    image: elasticsearch:5
    ports:
     - '127.0.0.1:9200:9200'

  kibana:
    image: kibana:5
    ports:
     - '127.0.0.1:5601:5601'
    links:
      - elasticsearch

  mta:
    build: mta/
    ports:
      - '22:22'
      - '25:25'
      - '587:587'
    volumes:
      - ./mta/shared:/opt/holonet
