# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 15:59
from __future__ import unicode_literals

import uuid

import basis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import holonet.apps.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=basis.models._now, editable=False)),
                ('updated_at', models.DateTimeField(default=basis.models._now, editable=False)),
                ('remote_identifier', models.CharField(db_index=True, max_length=32, unique=True)),
                ('domain', holonet.apps.utils.fields.DomainField(max_length=254, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=basis.models._now, editable=False)),
                ('updated_at', models.DateTimeField(default=basis.models._now, editable=False)),
                ('remote_identifier', models.CharField(db_index=True, max_length=32, unique=True)),
                ('list_name', holonet.apps.utils.fields.LocalPartField(max_length=254)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True, help_text='Allow postings to this list.')),
                ('archive', models.BooleanField(default=False, help_text='Archive all messages to this list in the message storage.')),
                ('processed_messages', models.BigIntegerField(default=0)),
                ('emergency', models.BooleanField(default=False, help_text='Emergency held all messages for moderation by the list admin.')),
                ('require_explicit_destination', models.BooleanField(default=True, help_text='Catch messages with wrong destination. This is typically bcc messages.')),
                ('last_post_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('member_posts', models.BooleanField(default=False, help_text='Only allow postings from list member addresses.')),
                ('include_rfc2369_headers', models.BooleanField(default=True)),
                ('anonymous_list', models.BooleanField(default=False, help_text='Remove sender address from postings to this list.')),
                ('subject_prefix', models.CharField(blank=True, help_text='Prefix subjects to this list.', max_length=100)),
                ('max_message_size', models.PositiveIntegerField(default=0, help_text='0 is unlimited.')),
                ('max_num_recipients', models.PositiveIntegerField(default=0, help_text='0 is unlimited.')),
                ('needs_manager_approval', models.BooleanField(default=False, help_text='All postages to this list needs approval in the admin panel')),
                ('use_verp', models.BooleanField(default=True)),
                ('verp_interval', models.PositiveIntegerField(default=10)),
                ('process_bounces', models.BooleanField(default=True)),
                ('domains', models.ManyToManyField(blank=True, to='lists.Domain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=basis.models._now, editable=False)),
                ('updated_at', models.DateTimeField(default=basis.models._now, editable=False)),
                ('remote_identifier', models.CharField(db_index=True, max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestrictedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=basis.models._now, editable=False)),
                ('updated_at', models.DateTimeField(default=basis.models._now, editable=False)),
                ('remote_identifier', models.CharField(db_index=True, max_length=32, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('from_address', models.EmailField(blank=True, max_length=254, verbose_name='From address')),
                ('timeout', models.DateTimeField(verbose_name='Timeout')),
                ('members', models.ManyToManyField(to='lists.ListMember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='list',
            name='members',
            field=models.ManyToManyField(to='lists.ListMember'),
        ),
    ]
