# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listmember',
            name='email',
        ),
    ]
